### ISSUE TITLE
Phoenix long type and Hbase incrementColumnValue

### ISSUE THREAD

**Issue by nmaillard** [forcedotcom/phoenix#157]
Hi everyone

I am running an M/R job to fill an Hbase table that I have previously declared through Phoenix. 
During this job I increment some columns.
During the query phase these incremented values I get back are inverted, I mean instead of 1 I get -95000 or to be more precises I get Long.maxvalue - value in table.

In the encode and decode long in the PdataType the sign bit is flipped. That is fine within phoenix since the reverse is done when reading and writing. But the Hbase incrementColumnvalue does not seem to have the same behaviour.

On a similar note  when I try to access a phoenix upserted hbase table through the standard Hbase API my LONG or INT will be flipped

regardes

**Comment by navdeepghotra** [comment]
Hi It is a big suggestion While Creating Table Schema in Phoenix , Please use data type UNSIGNED_LONG instead of INTEGER or BIGINT,

Because when you fetch a result from Phoenix, You will get exact values for what you are looking for.
