### ISSUE TITLE
Phoenix View on pre-existing HBase table?

### ISSUE THREAD

**Issue by doug-explorys** [forcedotcom/phoenix#316]
Hey there,

Can you create a Phoenix View on a pre-existing HBase table (i.e., one that is not created from Phoenix)?

It doesn't appear from the docs that you can, but I think this would be a very neat feature.  In fact, I would use this today if I could.  :-)

Doug

**Comment by manojoati** [comment]
Hi , Can we directly import RDBMS table into phoenix table , i know we can do sqoop import to hbase but i want to import that table into phoenix directly so that i will not have to create view for hbase table Please suggest.

**Comment by mravi** [comment]
Hi ,

   Can you please give it a try with the new MR integration support that is
being available from 4.3 v. Further details are mentioned here,
http://phoenix.apache.org/phoenix_mr.html. You can primarily use the
DBInputFormat or DataDrivenDBInputFormat as the InputFormat and
PhoenixOutputFormat for the writes to Phoenix to your job..

  We are working on supporting Sqoop , but in the mean time, writing a
custom MR job is your best bet.

Regards
Ravi

**Comment by Arjunk369** [comment]
I am unable read HBASE integer values from existing Table in PHOENIX
I tried with UNSIGNED_INT,UNSIGNED_LONG and other datatypes which provided for HBASE mapping
I acn read actual values from VARCHAR but I cant perform aggregation like SUM , AVG
SO anyone  know solution??
Kindly anyone tell how to read from existing HBASE TABLE integers

**Comment by Arjunk369** [comment]
How to map existing HBASE TABLE having integer values in phoenix to perform aggregation, 
I unable to get actual values through UNSIGNED_INT,UNSIGNED_LONG other hbase supported datatypes given on PHOENIX web site.

How to do anyone can reply

**Comment by mravi** [comment]
Hi Arjun,
     This forum is no more active. Please post to the User mailing list
http://phoenix.apache.org/mailing_list.html.

Also, can you take a screenshot of the result you see in your hbase shell
on a simple scan with a limit 1. This will help to know if you have stored
the integer values as String within HBase.

Regards
Ravi

**Comment by Arjunk369** [comment]
Thank you for Reply
please find attached Screen shot

**Comment by mravi** [comment]
Hi Arjun,
   I don't see any screenshot. Am I missing anything.

**Comment by Arjunk369** [comment]
Sir,

Please check attachment...
I have attached jpg file

**Comment by Arjunk369** [comment]
Sir,

Please find attached Screenshot with all step follwed while creating
Phoenix TBALE/VIEW from existing hbase table

/home/ist/Downloads/Screenshot_from_2015-04-14_11_28_34.jpg


​
Kindly update
Thanks & Regards
Arjun

**Comment by jtaylor-sfdc** [comment]
As Ravi already mentioned, this list is no longer active. Please subscribe
to our Apache mailing lists, as no further questions will be answered here.
For directions, see: http://phoenix.apache.org/mailing_list.html. Also,
there's plenty of previous mail threads that will help you diagnose your
issues, so I suggest you search those first: see the Search box on our home
page: http://phoenix.apache.org/

**Comment by Arjunk369** [comment]
Sir,

I am unable to find any solutions kindly update on same..

**Comment by mkanchwala** [comment]
Hi Guys,

I am trying to create a view on Existing HBase Table, Which is created successfully  but for INTEGER & DOUBLE, I got some encoded or corrupted values : 

CREATE VIEW DEMO_TABLE
(ROW_KEY VARCHAR PRIMARY KEY,
"info".SID INTEGER,
"info".GUID VARCHAR,
"info".VALUE DOUBLE,
"info".DATE_CREATED DATE);

An e.g | 72D117E1 | -2147448678 | C6E34C8BEBDA | -2| Wed Feb 07 00:00:00 UTC 2142 |

Can you please share your thoughts, what am I doing here?

**Comment by ankitbeohar90** [comment]
Hi All,

I have a Hbase table which I am accessing through Phoenix View. 
But if I am ingesting data into Hbase table through MR it is not reflected in Phoenix View. 
Please give the resolution.
