### ISSUE TITLE
Alias Insert to Upsert

### ISSUE THREAD

**Issue by Jerbell** [forcedotcom/phoenix#387]
It might be useful to be able to alias 'insert' commands as 'upsert' in Phoenix.
My specific reason for this is that I was trying to use DbDeploy for managing changes and internally it's coded to 'insert' into the changelog table.  There's no doubt other situations where it could be useful to insert.
A true/false property might be a good idea?
On the other hand, I can code around this and/or contact Graham the main contributor at DbDeploy.
What do people think?
Julian

**Comment by hepcibha** [comment]
Hi, I'm trying to use dbdeploy for Hbase db change management and I'm running into this issue, please see the error below. Has this been fixed? Can someone help me fix this issue, pls?

**Comment by jtaylor-sfdc** [comment]
Hello,
Phoenix moved to Apache a few years ago, so this site is no longer active.
If you have Phoenix questions, please subscribe to our Apache email list(s)
and ask there: https://phoenix.apache.org/mailing_list.html
Thanks,
James


On Feb 18, 2016, at 7:24 AM, hepcibha <notifications@github.com> wrote:

Hi, I'm trying to use dbdeploy for Hbase db change management and I'm
running into this issue, please see the error below. Has this been fixed?
Can someone help me fix this issue, pls?

—
Reply to this email directly or view it on GitHub
<https://github.com/forcedotcom/phoenix/issues/387#issuecomment-185772391>.

**Comment by hepcibha** [comment]
thanks !
