### ISSUE TITLE
Support the ability for a client to do query more

### ISSUE THREAD

**Issue by jtaylor-sfdc** [forcedotcom/phoenix#41]
Clients often need the ability to "page" through query results that have more row results than are displayable on a single screen. SQL provides LIMIT and OFFSET which is often used for this purpose, however supporting OFFSET in a performant manner is not possible with HBase. Instead, an alternate way of supporting query-more functionality (suggested by @lhofhansl) is through  [row values constructors](http://publib.boulder.ibm.com/infocenter/soliddb/v6r3/index.jsp?topic=/com.ibm.swg.im.soliddb.sql.doc/doc/row.value.constructors.html)  which has been in the SQL spec since SQL-92. It has PostGres support as well with the benefits explained well [here](https://wiki.postgresql.org/images/3/35/Pagination_Done_the_PostgreSQL_Way.pdf) .

**Comment by btz1211** [comment]
Just a quick question,
   Instead of doing offset, why can't Phoenix support the 'absolute' function in the resultset. I've seen many implementations doing pagination on the returned resultset using 'absolute'. Is there a reason it is not supported besides no one has come around to do it?

Thanks,

**Comment by jtaylor-sfdc** [comment]
This GitHub repo and issue list has been replaced by our Apache Phoenix
project and mailing lists. Please subscribe to one of these and repost your
question there: https://phoenix.apache.org/mailing_list.html


On Dec 2, 2015, at 7:09 PM, btz1211 <notifications@github.com> wrote:

Just a quick question,
Instead of doing offset, why can't Phoenix support the 'absolute' function
in the resultset. I've seen many implementations doing pagination on the
returned resultset using 'absolute'. Is there a reason it is not supported
besides no one has come around to do it?

Thanks,

—
Reply to this email directly or view it on GitHub
<https://github.com/forcedotcom/phoenix/issues/41#issuecomment-161502839>.
