### ISSUE TITLE
Is there a way to batch upsert values?

### ISSUE THREAD

**Issue by tcodehuber** [forcedotcom/phoenix#481]
Hi,
    These days I worked hard with phoenix. It is a great tool for us to fetch data from hbase. But I find that upserting rows into hbase using phoenix interface is not efficient. We seemingly can not set batch size. Is that true? "phoenix.muate.batchSize" is useful      for upsert select and delete, from wiki.

**Comment by Rsystems-GK** [comment]
Hi,
I have an issue with Apache Phoenix ,while upserting record in batch, please find below description of the issue.

there is a table **Case_Detail** and **SUSPECTED_NO_CASE_MAPPING**

1. **CREATE TABLE** CASE_DETAIL(case_Id BIGINT NOT NULL PRIMARY KEY,case_Name VARCHAR,case_Incharge VARCHAR,case_Date DATE,case_weedingDate DATE,case_decription VARCHAR,created_Date DATE,modified_Date DATE ,createdBy BIGINT ,modifiedBy BIGINT ,case_closeDate Date );

2. **CREATE TABLE** SUSPECTED_NO_CASE_MAPPING(id BIGINT NOT NULL PRIMARY KEY, case_Id BIGINT,SUSPECTED_NUMBER BIGINT);

First, I insert a row into case_detail and multiple rows in SUSPECTED_NO_CASE_MAPPING(mapping table) table using java client(Phoenix(phoenix-4.6.0-HBase-1.1) jdbc driver). it goes fine till now. But issue comes when I try to edit case_detail , to be more precise case_detail upsert is fine but batch update for mapping table doen’t work at all while the same code works fine during insert mode but get fail in edit and shows no error but data is not persisted in to hbase

below is java code(Spring boot jdbc Template) for the same.

//Query Strings usedin below code
      public static String **_INSERT_CASE_DETAIL_** = "upsert into CASE_DETAIL (CASE_ID,CASE_NAME,CASE_INCHARGE,CASE_DATE,CASE_WEEDINGDATE,CASE_DESCRIPTION,CREATED_DATE,MODIFIED_DATE,CREATEDBY,MODIFIEDBY,CASE_CLOSEDATE,ACCESS) values (NEXT VALUE FOR CASEDTL_ID,?,?,?,?,?,?,?,?,?,?,?)";

       public static String **_UPDATE_CASE_DETAIL_** = "upsert into CASE_DETAIL (CASE_ID,CASE_NAME,CASE_INCHARGE,CASE_DATE,CASE_WEEDINGDATE,CASE_DESCRIPTION,CREATED_DATE,MODIFIED_DATE,CREATEDBY,MODIFIEDBY,CASE_CLOSEDATE,ACCESS) values (?,?,?,?,?,?,?,?,?,?,?,?)";

     public final static String  **_UPDATE_SUSPECTED_NO_CASE_MAPPING_** = "UPSERT INTO SUSPECTED_NO_CASE_MAPPING(ID,CASE_ID,SUSPECTED_NUMBER) VALUES(NEXT VALUE FOR mobileNo_Case_Seq,?,?)";
	
	public static String _**INSERT_SUSPECTED_NO_CASE_MAPPING**_="UPSERT INTO SUSPECTED_NO_CASE_MAPPING(ID,CASE_ID,SUSPECTED_NUMBER) VALUES(NEXT VALUE FOR mobileNo_Case_Seq,CURRENT VALUE FOR CASEDTL_ID,?)";



if(null==cd.getCaseId())//INSERT Mode
	{
		retVal = jdbcTemplate.update(CaseDetail.INSERT_CASE_DETAIL,
				new Object[] {
                                           cd.getCaseName(), cd.getCaseIncharge(), cd.getCaseDate(),                     cd.getWeedingDate(),cd.getCaseDetails(),cd.getCreatedDate(),
cd.getModifiedDate(),cd.getCreatedBy(),cd.getModifiedBy(),cd.getCaseCloseDate(),cd.getAccess()
});			
}
                   else //UPDATE Mode
			{
				retVal = jdbcTemplate.update(CaseDetail.UPDATE_CASE_DETAIL,
						new Object[] {cd.getCaseId(),cd.getCaseName(), cd.getCaseIncharge(), cd.getCaseDate(), cd.getWeedingDate(),cd.getCaseDetails(),cd.getCreatedDate(),cd.getModifiedDate(),cd.getCreatedBy(),cd.getModifiedBy(),cd.getCaseCloseDate(),cd.getAccess()});
			}
		if(retVal!=0)
		{
						
				if (cd.getSuspectedNumbers() != null && cd.getSuspectedNumbers().size() > 0) {
					
					String qry=null;
					if(cd.getCaseId()==null)
						qry=CaseDetail.INSERT_SUSPECTED_NO_CASE_MAPPING;
					else
						qry=CaseDetail.UPDATE_SUSPECTED_NO_CASE_MAPPING;
					
					/*retVal = jdbcTemplate.update(qry,
							new Object[] {cd.getCaseId(),cd.getSuspectedNumbers().get(0).getPhoneNumber()});*/
							
				//UPSERT iNTO SUSPECTED_NO_CASE_MAPPING -- 
					jdbcTemplate.batchUpdate(qry,
							new BatchPreparedStatementSetter() {

								@Override
								public void setValues(PreparedStatement ps, int i) throws SQLException {
									if(cd.getCaseId()!=null)
										ps.setLong(2, cd.getCaseId());	
									
									ps.setLong(1, cd.getSuspectedNumbers().get(i).getPhoneNumber());									
								}

								@Override
								public int getBatchSize() {
									return cd.getSuspectedNumbers().size();
									// return 1;
								}
							});
					// jdbcTemplate.getDataSource().getConnection().commit();
				}

**Comment by navneetCompunnel** [comment]
Yes there is a way;
 Take a look at following working query:
Consider a table XYZ with columns ID,CF.RISK;

UPSERT INTO XYZ(ID,CF.RISK SELECT ID,(CASE ID WHEN '12341e65-a68b-4f88-93ce-33dd94497a6d' THEN 'MEDIUM_RISK' WHEN '73f41e65-a68b-4f88-93ce-33dd94497a6d' THEN 'HIGH_RISK' ELSE 'LOW_RISK' END) FROM ACCOUNTS WHERE ID IN('12341e65-a68b-4f88-93ce-33dd94497a6d','73f41e65-a68b-4f88-93ce-33dd94497a6d')
