### ISSUE TITLE
UPDATE TABLE Based on Condition

### ISSUE THREAD

**Issue by jhanit** [forcedotcom/phoenix#598]
Hi,
We have , 
1)UPSERT which update or insert a table ~ equivalent to insert of SQL+  Update of sql without condition.

2)UPSERT SELECT- can update table based on condition. looks similar to SQL update statement. But major difference is we can't update a table with new set of values as select will work on existing table i.e update temp with existing table values.

Common use case/ Issue:-
Update a table with new set of values based on condition, i.e 
UPSERT based on condition.

Can we have this common but very important feature of SQL?
Thanks,
Nitin

**Comment by saigeethamn** [comment]
Hi this seems like a issue closed long time but does not answer how we can do an UPSERT based on a condition like "UPSERT INTO EMP (NAME) VALUES ('XXX') WHERE EMPID = 123;
Instead we seem the need to have a table from which we can select and upsert.  Can we have a feature to just upsert based on a condition?
